# Docker Compose pour la production - Version simplifi√©e AMD64

services:
  # Frontend Next.js - Serveur unique - Architecture AMD64
  frontend:
    image: athenadecisionsystems/delphes-frontend:20251228-141152
    container_name: delphes-frontend-prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3006:3000" # Exposition directe du port Next.js
    environment:
      - NEXT_TELEMETRY_DISABLED=1
