apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: trusted-services
spec:
  selector:
    app: trusted-services-backend
  ports:
    - name: http
      port: 8002
      targetPort: 8002
  type: ClusterIP
