apiVersion: v1
kind: ConfigMap
metadata:
  name: trusted-services-config
  namespace: trusted-services
data:
  PYTHONUNBUFFERED: "1"
  NEXT_TELEMETRY_DISABLED: "1"
  BACKEND_INTERNAL_URL: "http://backend:8002"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_PORT: "8501"
