apiVersion: v1
kind: Service
metadata:
  name: delphes-frontend
  namespace: trusted-services
spec:
  selector:
    app: delphes-frontend
  ports:
    - name: http
      port: 3006
      targetPort: 3000
  type: LoadBalancer
